/**
 * This file is automatically generated.
 * Run "node ace schema:generate" after changing the database schema.
 */
import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AgriculturalPlotSchema extends BaseModel {
  @column() declare areaAcres: string | null
  @column() declare districtId: bigint | number
  @column({ isPrimary: true }) declare plotId: bigint | number
  @column() declare plotName: string
}

export class CropClimateWindowSchema extends BaseModel {
  @column() declare evapotranspiration: string
  @column() declare phase: string
  @column() declare rainfallMm: string
  @column() declare solarRadiation: string
  @column() declare statisticId: bigint | number
  @column() declare windSpeed: string
  @column({ isPrimary: true }) declare windowId: bigint | number
}

export class CropRotationRuleSchema extends BaseModel {
  @column() declare currentCropId: bigint | number
  @column() declare minimumBreakSeasons: number
  @column() declare recommendationReason: string
  @column() declare recommendedNextCropId: bigint | number
  @column({ isPrimary: true }) declare rotationRuleId: bigint | number
}

export class CropTemperatureRequirementSchema extends BaseModel {
  @column({ isPrimary: true }) declare cropId: bigint | number
  @column() declare maximumTemperatureC: string
  @column() declare minimumTemperatureC: string
  @column() declare preferredAverageTemperatureC: string
  @column() declare preferredHumidityPercent: string
}

export class CropSchema extends BaseModel {
  @column() declare biologicalNitrogenFixationKgHa: string
  @column() declare cropCategory: string
  @column({ isPrimary: true }) declare cropId: bigint | number
  @column() declare cropName: string
  @column() declare droughtTolerance: string
  @column() declare economicResilienceScore: string
  @column() declare estimatedWaterNeedMm: string
  @column() declare floodTolerance: string
  @column() declare growthPeriod: string
  @column() declare harvestPeriod: string
  @column() declare recommendedRotationRole: string
  @column() declare rootingDepth: string
  @column() declare salinityTolerance: string
  @column() declare soilHealthRole: string
  @column() declare soilHealthScore: string
  @column() declare waterConservationScore: string
  @column() declare waterDemandCategory: string
}

export class DistrictCropStatisticSchema extends BaseModel {
  @column() declare areaAcres: string
  @column() declare batchId: bigint | number
  @column() declare cropId: bigint | number
  @column() declare dataQualityStatus: string
  @column() declare districtId: bigint | number
  @column() declare productionMetricTonnes: string
  @column() declare reportedYieldMetricTonnesPerHectare: string
  @column() declare seasonId: bigint | number
  @column() declare sourceRowNumber: number
  @column({ isPrimary: true }) declare statisticId: bigint | number
  @column() declare transplantPeriod: string
}

export class DistrictRiskAssessmentSchema extends BaseModel {
  @column() declare batchId: bigint | number
  @column() declare districtId: bigint | number
  @column() declare droughtRisk: string
  @column() declare floodRisk: string
  @column({ isPrimary: true }) declare riskAssessmentId: bigint | number
  @column() declare salinityRisk: string
}

export class DistrictSeasonClimateSchema extends BaseModel {
  static table = 'district_season_climate'
  @column() declare averageEvapotranspiration: string
  @column() declare averageSolarRadiation: string
  @column() declare averageWindSpeed: string
  @column() declare batchId: bigint | number
  @column({ isPrimary: true }) declare climateId: bigint | number
  @column() declare districtId: bigint | number
  @column() declare rainfallMm: string
  @column() declare seasonId: bigint | number
}

export class DistrictSoilProfileSchema extends BaseModel {
  @column() declare batchId: bigint | number
  @column() declare districtId: bigint | number
  @column({ isPrimary: true }) declare profileId: bigint | number
  @column() declare soilNitrogenStatus: string
  @column() declare soilOrganicCarbonPercent: string
  @column() declare soilPh: string
  @column() declare soilTexture: string
}

export class DistrictSchema extends BaseModel {
  @column() declare agroEcologicalZone: string
  @column({ isPrimary: true }) declare districtId: bigint | number
  @column() declare districtName: string
  @column() declare divisionId: bigint | number
  @column() declare latitude: string
  @column() declare longitude: string
}

export class DivisionSchema extends BaseModel {
  @column({ isPrimary: true }) declare divisionId: bigint | number
  @column() declare divisionName: string
}

export class ExtremeWeatherEventSchema extends BaseModel {
  @column() declare affectedAreaAcres: string | null
  @column() declare districtId: bigint | number
  @column() declare estimatedCropLossMetricTonnes: string | null
  @column.date() declare eventEndDate: DateTime | null
  @column({ isPrimary: true }) declare eventId: bigint | number
  @column.date() declare eventStartDate: DateTime
  @column() declare eventType: string
  @column() declare notes: string | null
  @column() declare rainfallMm: string | null
  @column() declare severity: string | null
}

export class ImportBatchSchema extends BaseModel {
  @column({ isPrimary: true }) declare batchId: bigint | number
  @column.dateTime() declare importedAt: DateTime
  @column() declare notes: string | null
  @column() declare reportingYear: number | null
  @column() declare sourceFilename: string
  @column() declare sourceRowCount: number
  @column() declare sourceSha256: string
}

export class PlotCropHistorySchema extends BaseModel {
  static table = 'plot_crop_history'
  @column() declare cropId: bigint | number
  @column() declare cropYear: number
  @column({ isPrimary: true }) declare historyId: bigint | number
  @column() declare plotId: bigint | number
  @column() declare productionMetricTonnes: string | null
  @column() declare seasonId: bigint | number
}

export class SeasonSchema extends BaseModel {
  @column() declare description: string
  @column({ isPrimary: true }) declare seasonId: bigint | number
  @column() declare seasonName: string
}

export class SoilTestSchema extends BaseModel {
  @column() declare districtId: bigint | number
  @column() declare nitrogenStatus: string | null
  @column() declare salinityLevel: string | null
  @column.date() declare sampleDate: DateTime
  @column() declare soilOrganicCarbonPercent: string | null
  @column() declare soilPh: string | null
  @column({ isPrimary: true }) declare soilTestId: bigint | number
  @column() declare source: string | null
}

export class UserSchema extends BaseModel {
  @column.dateTime({ autoCreate: true }) declare createdAt: DateTime
  @column() declare email: string
  @column() declare fullName: string | null
  @column({ isPrimary: true }) declare id: number
  @column({ serializeAs: null }) declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true }) declare updatedAt: DateTime | null
}
