import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  async up() {
    await this.db.rawQuery(`
      CREATE TABLE import_batches (
        batch_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        source_filename text NOT NULL,
        source_sha256 char(64) NOT NULL UNIQUE,
        source_row_count integer NOT NULL CHECK (source_row_count >= 0),
        reporting_year integer,
        imported_at timestamptz NOT NULL DEFAULT now(),
        notes text
      );

      CREATE TABLE divisions (
        division_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        division_name text NOT NULL UNIQUE
      );

      CREATE TABLE seasons (
        season_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        season_name text NOT NULL UNIQUE,
        description text NOT NULL
      );

      CREATE TABLE districts (
        district_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        division_id bigint NOT NULL REFERENCES divisions(division_id),
        district_name text NOT NULL UNIQUE,
        latitude numeric(8,5) NOT NULL CHECK (latitude BETWEEN -90 AND 90),
        longitude numeric(8,5) NOT NULL CHECK (longitude BETWEEN -180 AND 180),
        agro_ecological_zone text NOT NULL
      );

      CREATE TABLE district_soil_profiles (
        profile_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        batch_id bigint NOT NULL REFERENCES import_batches(batch_id) ON DELETE CASCADE,
        district_id bigint NOT NULL REFERENCES districts(district_id) ON DELETE CASCADE,
        soil_texture text NOT NULL,
        soil_ph numeric(4,2) NOT NULL CHECK (soil_ph BETWEEN 0 AND 14),
        soil_organic_carbon_percent numeric(6,3) NOT NULL CHECK (soil_organic_carbon_percent >= 0),
        soil_nitrogen_status text NOT NULL CHECK (soil_nitrogen_status IN ('Very Low', 'Low', 'Medium', 'High', 'Very High')),
        UNIQUE (batch_id, district_id)
      );

      CREATE TABLE district_risk_assessments (
        risk_assessment_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        batch_id bigint NOT NULL REFERENCES import_batches(batch_id) ON DELETE CASCADE,
        district_id bigint NOT NULL REFERENCES districts(district_id) ON DELETE CASCADE,
        salinity_risk text NOT NULL CHECK (salinity_risk IN ('Non-Saline', 'Low', 'Moderate', 'High', 'Very High')),
        drought_risk text NOT NULL CHECK (drought_risk IN ('Low', 'Moderate', 'High', 'Very High')),
        flood_risk text NOT NULL CHECK (flood_risk IN ('Low', 'Moderate', 'High', 'Very High')),
        UNIQUE (batch_id, district_id)
      );

      CREATE TABLE crops (
        crop_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        crop_name text NOT NULL UNIQUE,
        crop_category text NOT NULL,
        growth_period text NOT NULL,
        harvest_period text NOT NULL,
        soil_health_role text NOT NULL,
        recommended_rotation_role text NOT NULL,
        biological_nitrogen_fixation_kg_ha numeric(10,3) NOT NULL CHECK (biological_nitrogen_fixation_kg_ha >= 0),
        water_demand_category text NOT NULL,
        estimated_water_need_mm numeric(10,3) NOT NULL CHECK (estimated_water_need_mm >= 0),
        rooting_depth text NOT NULL,
        drought_tolerance text NOT NULL,
        salinity_tolerance text NOT NULL,
        flood_tolerance text NOT NULL,
        soil_health_score numeric(4,2) NOT NULL CHECK (soil_health_score BETWEEN 0 AND 10),
        water_conservation_score numeric(4,2) NOT NULL CHECK (water_conservation_score BETWEEN 0 AND 10),
        economic_resilience_score numeric(4,2) NOT NULL CHECK (economic_resilience_score BETWEEN 0 AND 10)
      );

      CREATE TABLE crop_temperature_requirements (
        crop_id bigint PRIMARY KEY REFERENCES crops(crop_id) ON DELETE CASCADE,
        preferred_average_temperature_c numeric(5,2) NOT NULL,
        maximum_temperature_c numeric(5,2) NOT NULL,
        minimum_temperature_c numeric(5,2) NOT NULL,
        preferred_humidity_percent numeric(5,2) NOT NULL CHECK (preferred_humidity_percent BETWEEN 0 AND 100),
        CHECK (minimum_temperature_c <= preferred_average_temperature_c),
        CHECK (preferred_average_temperature_c <= maximum_temperature_c)
      );

      CREATE TABLE district_season_climate (
        climate_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        batch_id bigint NOT NULL REFERENCES import_batches(batch_id) ON DELETE CASCADE,
        district_id bigint NOT NULL REFERENCES districts(district_id) ON DELETE CASCADE,
        season_id bigint NOT NULL REFERENCES seasons(season_id),
        rainfall_mm numeric(12,3) NOT NULL CHECK (rainfall_mm >= 0),
        average_solar_radiation numeric(12,6) NOT NULL,
        average_wind_speed numeric(12,6) NOT NULL CHECK (average_wind_speed >= 0),
        average_evapotranspiration numeric(12,6) NOT NULL CHECK (average_evapotranspiration >= 0),
        UNIQUE (batch_id, district_id, season_id)
      );

      CREATE TABLE district_crop_statistics (
        statistic_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        batch_id bigint NOT NULL REFERENCES import_batches(batch_id) ON DELETE CASCADE,
        district_id bigint NOT NULL REFERENCES districts(district_id) ON DELETE CASCADE,
        crop_id bigint NOT NULL REFERENCES crops(crop_id),
        season_id bigint NOT NULL REFERENCES seasons(season_id),
        transplant_period text NOT NULL,
        area_acres numeric(16,3) NOT NULL CHECK (area_acres >= 0),
        production_metric_tonnes numeric(16,3) NOT NULL CHECK (production_metric_tonnes >= 0),
        reported_yield_metric_tonnes_per_hectare numeric(12,4) NOT NULL CHECK (reported_yield_metric_tonnes_per_hectare >= 0),
        source_row_number integer NOT NULL CHECK (source_row_number >= 2),
        data_quality_status text NOT NULL CHECK (data_quality_status IN ('ok', 'structural_zero', 'area_missing_for_positive_production')),
        UNIQUE (batch_id, district_id, crop_id)
      );

      CREATE TABLE crop_climate_windows (
        window_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        statistic_id bigint NOT NULL REFERENCES district_crop_statistics(statistic_id) ON DELETE CASCADE,
        phase text NOT NULL CHECK (phase IN ('pre_transplant', 'transplant', 'post_transplant')),
        rainfall_mm numeric(12,3) NOT NULL CHECK (rainfall_mm >= 0),
        solar_radiation numeric(12,6) NOT NULL,
        wind_speed numeric(12,6) NOT NULL CHECK (wind_speed >= 0),
        evapotranspiration numeric(12,6) NOT NULL CHECK (evapotranspiration >= 0),
        UNIQUE (statistic_id, phase)
      );

      CREATE TABLE extreme_weather_events (
        event_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        district_id bigint NOT NULL REFERENCES districts(district_id),
        event_type text NOT NULL CHECK (event_type IN ('flood', 'drought', 'cyclone', 'heatwave', 'salinity_intrusion', 'other')),
        event_start_date date NOT NULL,
        event_end_date date,
        severity text,
        rainfall_mm numeric(12,3),
        affected_area_acres numeric(16,3),
        estimated_crop_loss_metric_tonnes numeric(16,3),
        notes text,
        CHECK (event_end_date IS NULL OR event_end_date >= event_start_date)
      );

      CREATE TABLE soil_tests (
        soil_test_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        district_id bigint NOT NULL REFERENCES districts(district_id),
        sample_date date NOT NULL,
        soil_ph numeric(4,2) CHECK (soil_ph BETWEEN 0 AND 14),
        soil_organic_carbon_percent numeric(6,3) CHECK (soil_organic_carbon_percent >= 0),
        nitrogen_status text,
        salinity_level numeric(10,3),
        source text,
        UNIQUE (district_id, sample_date, source)
      );

      CREATE TABLE agricultural_plots (
        plot_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        district_id bigint NOT NULL REFERENCES districts(district_id),
        plot_name text NOT NULL,
        area_acres numeric(14,3) CHECK (area_acres > 0),
        UNIQUE (district_id, plot_name)
      );

      CREATE TABLE plot_crop_history (
        history_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        plot_id bigint NOT NULL REFERENCES agricultural_plots(plot_id) ON DELETE CASCADE,
        crop_id bigint NOT NULL REFERENCES crops(crop_id),
        season_id bigint NOT NULL REFERENCES seasons(season_id),
        crop_year integer NOT NULL,
        production_metric_tonnes numeric(14,3),
        UNIQUE (plot_id, crop_year, season_id)
      );

      CREATE TABLE crop_rotation_rules (
        rotation_rule_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        current_crop_id bigint NOT NULL REFERENCES crops(crop_id) ON DELETE CASCADE,
        recommended_next_crop_id bigint NOT NULL REFERENCES crops(crop_id) ON DELETE CASCADE,
        recommendation_reason text NOT NULL,
        minimum_break_seasons integer NOT NULL DEFAULT 0 CHECK (minimum_break_seasons >= 0),
        UNIQUE (current_crop_id, recommended_next_crop_id),
        CHECK (current_crop_id <> recommended_next_crop_id)
      );

      CREATE INDEX district_crop_statistics_district_idx ON district_crop_statistics (district_id);
      CREATE INDEX district_crop_statistics_crop_idx ON district_crop_statistics (crop_id);
      CREATE INDEX district_crop_statistics_season_idx ON district_crop_statistics (season_id);
      CREATE INDEX extreme_weather_events_district_date_idx ON extreme_weather_events (district_id, event_start_date);
      CREATE INDEX soil_tests_district_date_idx ON soil_tests (district_id, sample_date);

      CREATE VIEW district_crop_water_balance AS
      SELECT
        statistics.statistic_id,
        statistics.batch_id,
        districts.district_name,
        crops.crop_name,
        seasons.season_name,
        climate.rainfall_mm AS seasonal_rainfall_mm,
        crops.estimated_water_need_mm,
        climate.rainfall_mm - crops.estimated_water_need_mm AS water_balance_mm,
        statistics.area_acres,
        statistics.production_metric_tonnes,
        statistics.reported_yield_metric_tonnes_per_hectare
      FROM district_crop_statistics AS statistics
      JOIN districts USING (district_id)
      JOIN crops USING (crop_id)
      JOIN seasons USING (season_id)
      JOIN district_season_climate AS climate
        ON climate.batch_id = statistics.batch_id
       AND climate.district_id = statistics.district_id
       AND climate.season_id = statistics.season_id;

      CREATE VIEW district_portfolio_summary AS
      SELECT
        statistics.batch_id,
        districts.district_id,
        districts.district_name,
        divisions.division_name,
        SUM(statistics.area_acres) AS area_acres,
        SUM(statistics.production_metric_tonnes) AS production_metric_tonnes,
        SUM(statistics.production_metric_tonnes)
          / NULLIF(SUM(statistics.area_acres) * 0.40468564224, 0)
          AS calculated_yield_metric_tonnes_per_hectare,
        SUM(water.water_balance_mm * statistics.area_acres)
          / NULLIF(SUM(statistics.area_acres), 0) AS area_weighted_water_balance_mm
      FROM district_crop_statistics AS statistics
      JOIN districts USING (district_id)
      JOIN divisions USING (division_id)
      JOIN district_crop_water_balance AS water USING (statistic_id)
      GROUP BY statistics.batch_id, districts.district_id, districts.district_name, divisions.division_name;

      CREATE VIEW soil_health_change AS
      SELECT
        soil_test_id,
        district_id,
        sample_date,
        soil_ph,
        soil_organic_carbon_percent,
        soil_organic_carbon_percent
          - LAG(soil_organic_carbon_percent) OVER (PARTITION BY district_id ORDER BY sample_date)
          AS organic_carbon_change_percent,
        nitrogen_status,
        salinity_level
      FROM soil_tests;
    `)
  }

  async down() {
    await this.db.rawQuery(`
      DROP VIEW IF EXISTS soil_health_change;
      DROP VIEW IF EXISTS district_portfolio_summary;
      DROP VIEW IF EXISTS district_crop_water_balance;
      DROP TABLE IF EXISTS crop_rotation_rules;
      DROP TABLE IF EXISTS plot_crop_history;
      DROP TABLE IF EXISTS agricultural_plots;
      DROP TABLE IF EXISTS soil_tests;
      DROP TABLE IF EXISTS extreme_weather_events;
      DROP TABLE IF EXISTS crop_climate_windows;
      DROP TABLE IF EXISTS district_crop_statistics;
      DROP TABLE IF EXISTS district_season_climate;
      DROP TABLE IF EXISTS crop_temperature_requirements;
      DROP TABLE IF EXISTS crops;
      DROP TABLE IF EXISTS district_risk_assessments;
      DROP TABLE IF EXISTS district_soil_profiles;
      DROP TABLE IF EXISTS districts;
      DROP TABLE IF EXISTS seasons;
      DROP TABLE IF EXISTS divisions;
      DROP TABLE IF EXISTS import_batches;
    `)
  }
}
