/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Environment: () => import('#controllers/environment_controller'),
  Farms: () => import('#controllers/farms_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Recommendations: () => import('#controllers/recommendations_controller'),
  Session: () => import('#controllers/session_controller'),
}
